Traceback (most recent call last):
  File "/home/corrin/miniconda3/envs/book/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/corrin/miniconda3/envs/book/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/corrin/miniconda3/envs/book/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/corrin/miniconda3/envs/book/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/corrin/miniconda3/envs/book/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/corrin/miniconda3/envs/book/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/corrin/miniconda3/envs/book/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/corrin/miniconda3/envs/book/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
library(dplyr)
cancer <- read.csv('~/shared/data/cancer.csv')
cancer <- mutate(cancer, Class = factor(
                                    Class, 
                                    levels = c(0,1), 
                                    labels = c('benign', 'cancer')
                                    )
                 )

### Split data
training <- head(cancer,400)
test <- tail(cancer, nrow(cancer)- 400)

### Classifier function
# a is the marginal adhesion
# t is the thickness
classifier <- function (a, t){
    if(a>4){
        Class <- 'cancer' 
    } else if (t > 6){
        Class <- 'cancer'
    } else {
        Class <- 'benign'
    }
    Class
}
classifier <- Vectorize(classifier)

### Make predictions
test <- test %>%
        mutate(
            Prediction = classifier(
                                    Marginal.Adhesion, 
                                    Clump.Thickness
                                    )
            ) %>%
        select( 
               Marginal.Adhesion, 
               Clump.Thickness, 
               Prediction, 
               Class
              )
              
### Accuracy type function
# c is the class
# p is the prediction
accuracy_type <- function(c,p){
    if (c == p){
        tf <- 'true'
    } else {
        tf <- 'false'
    }
    
    if (p == 'cancer'){
        pn <- 'positive'
    } else {
        pn <- 'negative'
    }
    paste(tf,pn)
}
accuracy_type <- Vectorize(accuracy_type)


### Label accuracy type
test <- mutate(test, Accuracy = accuracy_type(Class, Prediction))

head(test,3)
------------------

Error in file(file, "rt"): cannot open the connection
Traceback:

1. read.csv("~/shared/data/cancer.csv")
2. read.table(file = file, header = header, sep = sep, quote = quote, 
 .     dec = dec, fill = fill, comment.char = comment.char, ...)
3. file(file, "rt")
ERROR: Error in file(file, "rt"): cannot open the connection


