Traceback (most recent call last):
  File "/opt/anaconda3/envs/FDTD/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/anaconda3/envs/FDTD/lib/python3.7/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/anaconda3/envs/FDTD/lib/python3.7/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/anaconda3/envs/FDTD/lib/python3.7/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/opt/anaconda3/envs/FDTD/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/anaconda3/envs/FDTD/lib/python3.7/site-packages/nbclient/client.py", line 559, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/anaconda3/envs/FDTD/lib/python3.7/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/anaconda3/envs/FDTD/lib/python3.7/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
for (i in 1:3) {
    ggsave(
        paste0(getwd(), '/images/L10_model_', i, '_plot.png'),
        plot_generator(
            filter(models, model == i), 
            paste('model', i)
        ),
        width=4,
        height=3,
        scale=0.4
    )
}
------------------

Error in grid.newpage(): could not open file '/home/clarkson/book/images/L10_model_1_plot.png'
Traceback:

1. ggsave(paste0(getwd(), "/images/L10_model_", i, "_plot.png"), 
 .     plot_generator(filter(models, model == i), paste("model", 
 .         i)), width = 4, height = 3, scale = 0.4)
2. grid.draw(plot)
3. grid.draw.ggplot(plot)
4. print(x)
5. print.ggplot(x)
6. grid.newpage()
ERROR: Error in grid.newpage(): could not open file '/home/clarkson/book/images/L10_model_1_plot.png'


